version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask

  dockergen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./certs:/etc/nginx/certs
      - nginx:/etc/nginx/conf.d

  dockerbridge:
    image: "openease/dockerbridge"
    container_name: dockerbridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - EASE_DEBUG=${EASE_DEBUG}

  postgres:
    image: "openease/postgres"
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker

  secret_init:
    image: "busybox"
    command: sh -c '< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c 64 > /etc/ease_secret/secret'
    volumes:
      - secret:/etc/ease_secret

  flask_css:
    image: "openease/css"
  flask_js:
    image: "openease/js"
  
  flask:
    image: "openease/flask"
    container_name: flask
    command: /opt/webapp/wait.sh postgres python runserver.py
    ports:
      - "5000:5000"
    links:
      - postgres
      - dockerbridge
      - flask_css
      - flask_js
      #- mongo_db
    volumes:
      - secret:/etc/ease_secret:ro
      #- /tmp/openEASE/dockerbridge
      ####
      #- /home/ros/mesh_data
    environment:
      - VIRTUAL_HOST=flask
      - VIRTUAL_PORT=5000
      - EASE_DEBUG=true
      # Workaround for container using legacy Docker links
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - DOCKERBRIDGE_PORT_5001_TCP_ADDR=dockerbridge
      - DOCKERBRIDGE_PORT_5001_TCP_PORT=5001
      #- *
      - OPENEASE_ADMIN_PASSWORD=${OPENEASE_ADMIN_PASSWORD}
      - OPENEASE_MAIL_USERNAME=${OPENEASE_MAIL_USERNAME}
      - OPENEASE_MAIL_PASSWORD=${OPENEASE_MAIL_PASSWORD}
      - OPENEASE_MESHES=${OPENEASE_MESHES}
      - OPENEASE_ROS_DISTRIBUTION=${OPENEASE_ROS_DISTRIBUTION}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_SECRET=${GITHUB_APP_SECRET}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - TWITTER_APP_ID=${TWITTER_APP_ID}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET}
      - GOOGLE_APP_SECRET=${GOOGLE_APP_SECRET}
      - GOOGLE_APP_ID=${GOOGLE_APP_ID}
volumes:
  secret:
  postgres:
  nginx:

